# docker compose up -d

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/inputlogs/*.log
    fields_under_root: true
    fields:
      log_type: ssh_simulated
    multiline.type: pattern
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

processors:
  - rename:
      fields:
        - from: "message"
          to: "event.original"
      ignore_missing: true
      fail_on_error: false
  - copy_fields:
      fields:
        - from: "event.original"
          to: "message"
        - from: "event.original"
          to: "log_summary"
      fail_on_error: false
  - dissect:
      tokenizer: "[%{timestamp}] %{environment}.%{level}: %{msg} %{json_tail}"
      field: "message"
      target_prefix: "parsed"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"